version: "3"
services:
  jwt-db:
    image: postgres:11
    container_name: jwt-db
    restart: always
    environment:
      - POSTGRES_DB=jwt-db
      - POSTGRES_USER=master
      - POSTGRES_PASSWORD=master
    ports:
      - 5492:5432
